// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       throw UnsupportedError(
//         'DefaultFirebaseOptions have not been configured for web - '
//         'you can reconfigure this by running the FlutterFire CLI again.',
//       );
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions android = FirebaseOptions(
//       apiKey: "AIzaSyCbkxykhs9Qi9wxTS3VxqIRbjvU_BtGAew",
//       authDomain: "ryderz-ef4ce.firebaseapp.com",
//       projectId: "ryderz-ef4ce",
//       storageBucket: "ryderz-ef4ce.appspot.com",
//       messagingSenderId: "467906466590",
//       appId: "1:467906466590:web:983319870a97d175a7ef0f",
//       measurementId: "G-JN6CVJ3WMC");
// //  it's is incomplete
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyCbkxykhs9Qi9wxTS3VxqIRbjvU_BtGAew',
//     appId: '1:467906466590:web:983319870a97d175a7ef0f',
//     messagingSenderId: '467906466590',
//     projectId: 'ryderz-ef4ce',
//     storageBucket: 'ryderz-ef4ce.appspot.com',
//     iosClientId:
//         '520692343980-5o3bmdgu1l3d05pgaptoenccdoucrj8n.apps.googleusercontent.com',
//     iosBundleId: 'com.example.ryderz',
//   );
// }
